### ISSUE TITLE
I'm looking to use this in C# Unity if you know can I still build cross platform with this?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [nickbabcock/Pfim#25]
Forgive me if this is a silly question, am I correct in my understanding that this can be used in Unity?

I'll come back and comment/close once I've tried it out and know for sure.

This has lib/FreeImage.dll but that only appears to be used for the Benchmarks so I think it would be fine to just take the parsing code.

I also see some unsafe and fixed it appears I can set Unity to allow that so it might be ok.

My need:
I'm looking to load DDS3 and DDS1 textures, Unity does not support DDS3 anymore, I've tried two other attempts based off the same code to parse DDS and they fail to handle these as they just load the DDS Header and pass the raw data bytes to the raw texture load. Started coding my own decompression of the block last night but got too tired, thought I would give it a better googling and found your project yay!

Use case:
Thinking to output a texture atlas from many different textures all for the same mesh including mip maps, padding and repeating the perimeter of the individual textures into the padding.

So ideally I would like to read the 32bit RGBA of each file.

From looking at your source this seems suitable.
Dxt1Dds would decode as Rgb24
Dxt3Dds would decode as Rgba32

**Comment by LiamKarlMitchell** [comment]
It seems System.Drawing, Bitmap and other things are not available might need to swap out their usages and port for Unity's equivalents bummer.

**Comment by LiamKarlMitchell** [comment]
Well I've done some porting of just the dds parts to use Texture 2D and have my DDS's loading in Unity including the ones that had problems with alpha. Very nice :) thanks for this code.

I had to flip the colors when saving to data as it was inverted.
BGR rather than RGB.

May also be a unity bug to work around as I've read this in the previous codes I tried.

> Work around for an >Unity< Bug.
> if QualitySettings.masterTextureLimit != 0 (half or quarter texture rez)
> and dwWidth and dwHeight divided by 2 (or 4 for quarter rez) are not a multiple of 4 
> and we are creating a DXT5 or DXT1 texture
> Then you get an Unity error on the "new Texture"

**Comment by nickbabcock** [comment]
Yeah I have used this in a unity project, though that was a couple years ago. If there is anything that makes usage in Unity easier, I'm all ears.

**Comment by LiamKarlMitchell** [comment]
Happy to fork and do a pull request for modifications that made it work for me in Unity perhaps on a different branch?

I copy pasted the checked out code into a directory in Assets of my Unity project and deleted folders/files that were not required.

Perhaps a more suitable way would be to make a release from a Branch on this repo as an AssetBundle specifically for Unity that way the project would be easier to find and use for others that need to load older files like my self.

Had thought about using as DLL plugin but would thought it an unnecessary complexity when the C# code should drop in just fine..

Have ignored TGASharpLib and TargaImage.cs for now, but I'll probably do them later down the road.


Do you know if this is an appropriate way to check if the code is being compiled for Unity?
```cs
#if UNITY_5_3_OR_NEWER`
``

I have made tweaks like this.
```cs
#if UNITY_5_3_OR_NEWER
                    // Note: For unity need to switch the R and B around.
                    data[dataIndex++] = col.b;
                    data[dataIndex++] = col.g;
                    data[dataIndex++] = col.r;
#else
                    data[dataIndex++] = col.r;
                    data[dataIndex++] = col.g;
                    data[dataIndex++] = col.b;
#endif
```

Added in an enum for PixelFormat as that was missing.

No arrow method shorthand available. (There would be a more appropriate .NET version define to check this #if NETSTANDARD1_3).

```cs
#if UNITY_5_3_OR_NEWER
        public DdsPixelFormat PixelFormat{
            get {
                return pixelFormat;
            }
            set
            {
                pixelFormat = value;
            }
        }
#else
        /// <summary>
        /// The pixel format 
        /// </summary>
        public DdsPixelFormat PixelFormat
        {
            get => pixelFormat;
            set => pixelFormat = value;
        }
#endif
```

Added a get on the Dds class to map between ImageFormat and TextureFormat where applicable.
```cs
#if UNITY_5_3_OR_NEWER
        public TextureFormat TextureFormat {
            get {
                switch (Format)
                {
                    case ImageFormat.Rgba16:
                        return TextureFormat.RGBAHalf;
                    case ImageFormat.Rgb24:
                        return TextureFormat.RGB24;
                    case ImageFormat.Rgba32:
                        return TextureFormat.RGBA32;
                    default:
                        throw new NotImplementedException("ImageFormat " +Format.ToString()+ " to TextureFormat is not implemented.");
                }
            }
            set {
                throw new NotImplementedException("Setting the Texture Format is not implemented.");
            }
        }
#endif
```


Should add a method to parse and Texture2D for something like this, with overloaded methods for Stream, FilePath as well.
```
public static Texture2D LoadDDS(byte[] ddsBytes, bool updateMipMaps = false, bool makeNoLongerReadable = true)
PfimConfig pfimConfig = new PfimConfig();
Dds dds = Dds.Create(ddsBytes, pfimConfig);
dds.Decompress();

texture = new Texture2D(dds.Width, dds.Height, dds.TextureFormat, dds.Header.MipMapCout == 0);
texture.LoadRawTextureData(dds.Data);
texture.Apply(updateMipMaps, makeNoLongerReadable);
return texture;
```

**Comment by nickbabcock** [comment]
Some thoughts

- Since Pfim targets .netstandard 1.0, so it'll work in a [host of environments](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) including .net 4.5. 
- [Unity 2018.1](https://blogs.unity3d.com/2018/03/28/updated-scripting-runtime-in-unity-2018-1-what-does-the-future-hold/) supports .net core 2.0 and .NET 4.x.
- But as you noted, Unity doesn't support expression bodied property setters ([introduced in C# 7.0](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members)), as Unity 2018.1 supports up to C# 6.0
- However, the use of C# language features is tangential to platform APIs exposed (so while Pfim uses C# 7, it only uses .netstandard 1.0 APIs), so the dll is compatible with all environments (including Unity 2018.1)
- But you mentioned avoiding dlls, but have you checked out [NugetForUnity](https://github.com/GlitchEnzo/NuGetForUnity)? It appears well maintained and popular, so one should be able to work with nuget packages
- I'm wary about creating a branch dedicated to unity as that branch will probably be treated second class due to me not being a Unity developer. To me, this adds more maintenance burden that what it's worth (taking into consideration previous points)
- I prefer to keep Pfim dependency free, so any unity APIs would need to be extracted into a separate package or shown in an example like [Pfim.Viewer.Forms](https://github.com/nickbabcock/Pfim/blob/22f5b29e1f538806a7eec4f7ca30066c8389168d/src/Pfim.Viewer.Forms/Form1.cs)
- I'm not sure what the best solution is for the reversed rgb channels in Unity vs WPF & WinForms API (I'm curious if there is additional information out there about the differences). As if rgb channels are reversed, I'm assuming the logic should reversed in other parts of the code too for unity. It doesn't seem right to compile (`ifdef`) the logic as that may be too heavy handed of an approach.

So my preference is:

- See if using nuget inside of Unity works. Then one would have to swap the channels in userspace
- If that is not good, I'd accept a PR setting the langversion to `6` (still would have to swap channels in userspace)

**Comment by nickbabcock** [comment]
I'm going to close this with the proposed solution being use the dll, as that method still seems the most popular in Unity, but I'm happy to continue the conversation

**Comment by LiamKarlMitchell** [comment]
Cheers, I'll keep it in mind will have to try if the DLL works :)
