### ISSUE TITLE
Uneven Compressed DDS Images produce strange results

### ISSUE THREAD

**Issue by draconas1** [nickbabcock/Pfim#51]
Heya,

Thanks for the update that decoded uneven DDS files, however on use the images I get out are badly distorted.  
I have put the DDS with the resulting output PNGs here: https://drive.google.com/drive/folders/1NRYCqqh1C_vvLgKUHQxzoVXYq6g2CGfc?usp=sharing 

(Entirely possible that this is because I am using pfim or IM incorrectly for uneven DDS files, but it works fine for all the others)

Code I am using:
```c#
var ddsImage = Pfim.Pfim.FromFile(inputPath);
if (ddsImage.Compressed) {
    ddsImage.Decompress();
}

switch (ddsImage.Format) {
    case Pfim.ImageFormat.Rgba32:
        Image.LoadPixelData<Bgra32>(ddsImage.Data, ddsImage.Width, ddsImage.Height).Save(outputPath);
        return true;
    case Pfim.ImageFormat.Rgb24:
        Image.LoadPixelData<Bgr24>(ddsImage.Data, ddsImage.Width, ddsImage.Height).Save(outputPath);
        return true;
    default:
        Log.Logger.Warning("Image {inputPath} had unknown format {format}", inputPath, ddsImage.Format);
        return false;
}
```

Image is from SixLabors.ImageSharp

**Comment by nickbabcock** [comment]
Pfim is able to display the image fine:

![image](https://user-images.githubusercontent.com/2106129/56291916-c3332200-60eb-11e9-860e-bb36baa721e3.png)

So this narrows it down to differences between ImageSharp and Pfim. I do not use ImageSharp, so this is mainly a hypothesis:

I'm assuming that ImageSharp expects the data array to have a length of Height * Width * Depth. While this is the most intuitive, Pfim data array contains a few areas of extra space:

- Image libraries like Windows GDI+ and Cairo expect alignment of rows to be a multiple of 4 bytes. This padding allows for more efficient processing of an image and is harmless, as these libraries know where the next line of pixel data starts by looking at an image's stride.
- When dealing with block based images like the dds image you've posted, Pfim size up a partially unused block. For instance, the image is 98x98, but internally Pfim decodes it as 100x100 due to 4x4 not fitting. The 2 pixels added to the width are encompassed in the image's stride and the bottom 2 pixel rows are present but unused.
- And once #50 is merged, and one opts into some sort of buffer pooling, there may be even more unused bytes at the end of the pixel data.

Since ImageSharp does not accept an image's stride as an argument (in contrast to Windows GDI+'s (`new Bitmap`), Cairo's (`create_for_data`), and DirectX textures (WPF's BitmapSource)), it appears that ImageSharp can't handle any image with padding. One way to workaround this would be to create a new data array that strictly contains only the pixel data:

```csharp
var tightStride = (image.Width * image.BitsPerPixel + 7) / 8;
byte[] newData = new byte[image.Height * tightStride];
for (int i = 0; i < image.Height; i++)
{
    Buffer.BlockCopy(image.Data, i * image.Stride, newData, i * tightStride, tightStride);
}
SixLabors.ImageSharp.Image.LoadPixelData<Bgra32>(newData, image.Width, image.Height).Save(fs, new PngEncoder());
```

All those copies are unfortunate (in my opinion ImageSharp should improve on this), but I tested the snippet with your image and it appears correctly. It is possible that no copying is needed if one detects no padding in the stride:

```csharp
byte[] newData;

// Since image sharp can't handle data with line padding in a stride
// we create an stripped down array if any padding is detected
var tightStride = (image.Width * image.BitsPerPixel + 7) / 8;
if (image.Stride != tightStride)
{
    newData = new byte[image.Height * tightStride];
    for (int i = 0; i < image.Height; i++)
    {
        Buffer.BlockCopy(image.Data, i * image.Stride, newData, i * tightStride, tightStride);
    }
}
else
{
    newData = image.Data;
}

// TODO: Implement logic to select appropriate image sharp pixel format
SixLabors.ImageSharp.Image.LoadPixelData<Bgra32>(newData, image.Width, image.Height).Save(fs, new PngEncoder());
```

Cheers, I may look to add a simple ImageSharp example to the repo for those using it.

**Comment by draconas1** [comment]
Worked like a charm.   Many thanks :)
( the output result BTW is here https://www.draconas.co.uk/stellaristech/ )
