### ISSUE TITLE
Color channels are swapped when loaded from *.tga

### ISSUE THREAD

**Issue by ActuallyaDeviloper** [nickbabcock/Pfim#6]
Sorry that there is already a new problem, but now the image that previously resulted in an infinite loop (issue #5) appears to have the red and blue color channel swapped.

A test image file:
[Alps.zip](https://github.com/nickbabcock/Pfim/files/1432431/Alps.zip)

**Comment by nickbabcock** [comment]
Weird, I have a comment specifically saying that they should be swapped, but unswapping the values makes the image turn out correctly. All test cases pass, so I'm guessing it's just my unfamiliarity with TopLevel encoded Targa images. Since it greatly simplifies the code, I'm not complaining 😆 

I'll cut 0.4.4 tonight. Benchmarks show 20x improvement.

**Comment by nickbabcock** [comment]
0.4.4 released:

![image](https://user-images.githubusercontent.com/2106129/32253182-9767c270-be67-11e7-9dea-50681d20a21d.png)
